### ISSUE TITLE
Null reference error

### ISSUE THREAD

**Issue by amalshashika** [YnotZer0/unity3d_watsonSdk#2]
Hi Tony,

I am getting this System.NullReferenceException: Object reference not set to an instance of an object
  at Watson_Service.set_Active (Boolean value) [0x000f6] exception in line 258. All 3 connections are successful. Please advice.

Further,
[12/14/2018 07:05:55][Unity][CRITICAL] Unity Exception NullReferenceException: Object reference not set to an instance of an object : Watson_Service.set_Active (Boolean value) (at Assets/Scripts/Watson_Service.cs:258)
Watson_Service.Update () (atScripts/Watson_Service.cs:551)

UnityEngine.Debug:LogError(Object)
IBM.Watson.DeveloperCloud.Debug.DebugReactor:ProcessLog(LogRecord) (at Assets/Watson/Scripts/Debug/DebugReactor.cs:60)
IBM.Watson.DeveloperCloud.Logging.LogSystem:ProcessLog(LogRecord) (at Assets/Watson/Scripts/Logging/Logger.cs:206)
IBM.Watson.DeveloperCloud.Logging.Log:Critical(String, String, Object[]) (at Assets/Watson/Scripts/Logging/Logger.cs:294)
IBM.Watson.DeveloperCloud.Logging.LogSystem:UnityLogCallback(String, String, LogType) (at Assets/Watson/Scripts/Logging/Logger.cs:167)
UnityEngine.Application:CallLogCallback(String, String, LogType, Boolean)

![image](https://user-images.githubusercontent.com/34933125/49987909-0d1fc600-ff9b-11e8-871e-0acc0240b32a.png)

**Comment by YnotZer0** [comment]
I believe we covered this issue in the comments of the developerWorks article

**Comment by amalshashika** [comment]
Thank You! Tony. Much appreciated.
